export { default as HelperChat } from './Pomoshnik/mobile/Chat'
export { default as MainPolicy } from './PolicyPage/mobile/MainPolicy'
export { default as MobilePolicy } from './PolicyPage/mobile/Policy'
export { default as CreatePolicyDirectory } from './PolicyPage/mobile/PolicyDirectory/CreatePolicyDirectory'
export { default as EditPolicyDirectories } from './PolicyPage/mobile/PolicyDirectory/EditPolicyDirectory'
export { default as MainPost } from './PostPage/mobile/MainPost'
export { default as Posts } from './PostPage/mobile/Posts'
export { default as NewPosts } from './PostPage/mobile/NewPosts'
export { default as AttachStatistics } from './PostPage/mobile/AttachStatistics/AttachStatistics'
export { default as MainStrategy } from './StrategyPage/mobile/MainStartegy'
export { default as MobileStrategy } from './StrategyPage/mobile/Strategy'
export { default as MobileGoal } from './GoalPage/mobile/Goal'
export { default as MobileObjective } from './ObjectivePage/mobile/Objective'
export { default as MainProject } from './ProjectPage/mobile/MainProject/MainProject'
export { default as Projects } from './ProjectPage/mobile/Projects'
export { default as NewProject } from './ProjectPage/mobile/NewProject/NewProject'
export { default as Programs } from './ProjectPage/mobile/Programs'
export { default as ProjectArchive } from './ProjectPage/mobile/Archive/ProjectArchive'
export { default as MainStatistics } from './StatisticsPage/mobile/MainStatistics'
export { default as Statistics } from './StatisticsPage/mobile/Statistics'
export { default as MobileMainWorkingPlan } from './WorkingPlanPage/mobile/MainWorkingPlan'
export { default as MobileMain } from './Main/Main'
export { default as MobileControlPanel } from './ControlPanel/mobile/ControlPanel'
export { default as AuthorizationPage } from './Authorization/Main'
export { default as User } from './UserPage/mobile/User'
export { default as DialogPage } from './DialogPage/DialogPage.jsx'
export { default as WatcherDialogPage} from './DialogPage/WatcherDialogPage/WatcherDialogPage.jsx'
export { default as AgreementDialogPage} from './DialogPage/AgreementDialogPage/AgreementDialogPage.jsx'
export { ConvertsPage } from './ConvertsPage//ConvertsPage.jsx'
export { default as CompanySchema } from './CompanySchema/mobile/CompanySchema'
export { default as SchemeСompanies } from './CompanySchema/mobile/schemeСompanies/SchemeСompanies'
export { default as PostSchema } from './CompanySchema/mobile/postSchema/PostSchema'
export { default as SettingsPage } from './SettingsPage/mobile/SettingsPage.jsx'
export {default as ArchiveDialog} from './DialogPage/ArchiveDialog/ArchiveDialog.jsx'


